- .github/dependabot.yml
- .github/workflows/linting.yml
- LICENSE
- docs/conf.py
- docs/index.md
* Create dependabot.yml
* Create linting.yml
* Update conf.py
* typo ROCM
* Update LICENSE to add AMD
* spelling
* Update conf.py
* Update requirements.txt
* link
* Update conf.py
* Update conf.py
* Update conf.py
* Update conf.py
* Testing
* Update conf.py
* Update conf.py
* Update docs/conf.py
* Testing with fork
* Reduce options
* upstream rocm-docs-core
* Cleanup
(cherry picked from commit 8d7a5a72bea55a69e1818c89c3d2af5d02b6cac1)
> Cherry-pick to apply Instinct flavor

- docs/index.md
- docs/installation/kubernetes-helm.md
- docs/specialized_networks/airgapped-install.md
- docs/specialized_networks/http-proxy.md
1. We have setup the Helm repository on rocm.github.io/gpu-operator
2. Update related helm commands in the documentation
> Update helm commands in docs

- .gitignore
- docs/installation/openshift-helm.md
- docs/installation/openshift-olm.md
- docs/releasenotes.md
- docs/sphinx/_toc.yml
- docs/sphinx/_toc.yml.in
Added missing OpenShift Installation docs
> Added OpenShift Installation documentation

- tools/techsupport_dump.sh
1. Enhance the cleanup function to remove temporary daemonset, use ```trap``` to make sure it always gets executed no matter how the script exits.
2. Fix the filter to retrieve operator pod information.
> Fix techsupport_dump script

- docs/fulldeviceconfig.rst
- docs/sphinx/_toc.yml
- docs/sphinx/_toc.yml.in
Updated documentation to include the reference config examples for the GPU Operator DeviceConfig.
> Added Full Reference Config to documentation

- docs/fulldeviceconfig.rst
- docs/knownlimitations.md
- docs/releasenotes.md
- docs/upgrades/upgrade.md
- docs/usage.md
- helm-charts/README.md
* Updated Full Device Config to include new fields from v1.2.0 release
* Updated Release notes with Document Updates section
* Fixed Helm upgrade command in Driver Upgrade section
* Updated Quick Start guide to fix version issue and remove label step which is no longer needed
> Updated FullDeviceConfig, Release Notes, Upgrade and Quick Start docs

- Makefile
- README.md
- docs/contributing/developer-guide.md
- docs/sphinx/_toc.yml
- docs/sphinx/_toc.yml.in
- tests/e2e/utils/init.go
1. Tested to make sure external developers could compile to build the operator artifacts.
2. Tested to make sure external developers could deploy the operator from self built artifacts.
3. Optimize the Makefile description, now everyone can use ```make help``` to dump more detailed descriptions regarding the make target.
4. Minor change on the developer guide docs, add developer guide docs to be indexed by the documentation website.
```
output of make help:
Usage:
make <target>
QuickStart
default          Quick start to build everything from docker shell container.
docker/shell     Bring up and attach to a container that has dev environment configured.
General
help             Display this help.
Development
manifests        Generate ClusterRole and CustomResourceDefinition objects. …
```
> Amend commit to opensource AMD GPU Operator

- grafana/dashboard_gpu.json
- grafana/dashboard_job.json
- grafana/dashboard_node.json
- grafana/dashboard_overview.json
update hostnames list after cluster_name selection
sync grafana dashboards changes up to https://github.com/pensando/device-metrics-exporter/pull/309
> update hostnames with cluster_name selection

- api/v1alpha1/deviceconfig_types.go
- bundle/manifests/amd-gpu-operator.clusterserviceversion.yaml
- bundle/manifests/amd.com_deviceconfigs.yaml
- config/crd/bases/amd.com_deviceconfigs.yaml
- config/manifests/bases/amd-gpu-operator.clusterserviceversion.yaml
- helm-charts-k8s/Chart.lock
- helm-charts-k8s/crds/deviceconfig-crd.yaml
- helm-charts-openshift/Chart.lock
- helm-charts-openshift/crds/deviceconfig-crd.yaml
- internal/nodelabeller/nodelabeller.go
Repush https://github.com/ROCm/gpu-operator/pull/102 to staging branch
> Optimize the docs and filename for blacklist function

- docs/conf.py
- docs/requirements.txt
- docs/sphinx/requirements.in
- docs/sphinx/requirements.txt
- Updated rocm-docs-core to newer version
- Updated RTD theme to 'instinct' to support Copy button on all code blocks in docs
> Updated ReadTheDocs conf to support copy button in code blocks

- internal/controllers/upgrademgr.go
Enhancement: Select pods where user could have manually mounted gpu folders directly as well (anything under /dev/dri)
> pod eviction/deletion selection enhancement

- docs/knownlimitations.md
- docs/releasenotes.md
- docs/sphinx/_toc.yml.in
- docs/test/logs-export.md
Release notes for v1.2.1 release, documentation for the new beta feature of logs-export have been added.
> V1.2.1 release docs

- docs/knownlimitations.md
- docs/releasenotes.md
- docs/sphinx/_toc.yml.in
- docs/test/logs-export.md
Release notes for v1.2.1 release, documentation for the new beta feature of logs-export have been added.
> Added release notes, logs-export doc, and updated known limitations for the latest v1.2.1 release.

- internal/kmmmodule/kmmmodule.go
- internal/kmmmodule/kmmmodule_test.go
Verified that all unit test cases passed.
> Continue building kernel map when partial nodes have unsupported OS

- tools/techsupport_dump.sh
1. Add uuid to each techsupport run, so that each run will only utilizing its own temp file and debug pods, they won't affect each other
2. Remove ```-it``` from ```kubectl exec -it``` so that users could run the techsupport script in the background without waiting for users input.
> Add support for concurrent techsupport run

- docs/installation/openshift-olm.md
Port https://github.com/ROCm/gpu-operator/pull/204 to v1.2.1
> [DOC] Update docs for Openshift NodeFeatureDiscovery instruction

- internal/controllers/upgrademgr.go
cp of pensando/gpu-operator#750
> [CP 750] [CP 749] Drain DP and NL along with ME and DCM before upgrade

- internal/controllers/upgrademgr.go
cp of pensando/gpu-operator#754
> [CP 754] [CP 751] Drain TR

- docs/installation/openshift-olm.md
Addressing Suggestion from Issue https://github.com/ROCm/gpu-operator/issues/222
> [CP 760][DOC] Document different scenarios for configuring OpenShift NFD Operator

- docs/specialized_networks/airgapped-install-openshift.md
- docs/specialized_networks/airgapped-install.md
- docs/sphinx/_toc.yml
- docs/sphinx/_toc.yml.in
cp of pensando/gpu-operator#795
> [CP 795] New Openshift specific documentation for airgapped environments.

- docs/conf.py
cp of pensando/gpu-operator#809
> [CP 809] [Docs] add repository_url in the conf.py

- internal/configmanager/configmanager.go
- internal/metricsexporter/metricsexporter.go
- internal/testrunner/testrunner.go
(cherry picked from commit 0d88d36836649273e545233a19bdb61d7a14f97d)
> [Fix] Fix possible panic when handling metrics exporter (#830)

- docs/usage.rst
cp of pensando/gpu-operator#821
> [CP 821] [Docs] Fix installation links on usage doc page

- docs/dcm/applying-partition-profiles.rst
- docs/dcm/device-config-manager-configmap.md
- docs/dcm/systemd_integration.md
- docs/sphinx/_toc.yml
- docs/sphinx/_toc.yml.in
- example/configManager/config.json
(cherry picked from commit 5389d38c6a9efbb7680ac74c28a874aef221728a)
> [GPUOP] Adding docs for DCM Systemd integration (#851) (#852)

- docs/conf.py
v1.4.0 is still in development, put a notice for the docs on that branch.
> [DOC] Add announcement for in-development doc branch

- docs/conf.py
- docs/test/agfhc.md
- docs/test/test-runner-overview.md
Amend more details and warning regarding the proper usage of AGFHC in docs.
> [CP 916][DOC] Add more wanring and description regarding the AGFHC docs

- internal/controllers/mock_remediation_handler.go
- internal/controllers/remediation_handler.go
cp of pensando/gpu-operator#915
> [CP 915] remediation workflow - misc fixes

- docs/conf.py
- docs/sphinx/_toc.yml
- docs/sphinx/_toc.yml.in
Make the docs website left side navigation bar collapsed by default for better readability.
> [DOC] Collapse navigation bar

- docs/test/pre-start-job-test.md
we need to specify
```yaml
limits:
amd.com/gpu: 8
```
otherwise the system would show warning and won't create the job resource in k8s.
> [DOC] fix pre-start job check test runner doc

- config/samples/amd.com_deviceconfigs.yaml
- docs/drivers/installation.md
- docs/drivers/precompiled-driver.md
- docs/fulldeviceconfig.rst
- docs/installation/kubernetes-helm.md
- docs/releasenotes.md
- docs/specialized_networks/airgapped-install-openshift.md
- example/deviceconfig_example.yaml
> Cherry-pick v1.4.0 release notes commits

- docs/conf.py
> [DOC] Remove in-development notice for v1.4.0 docs
