example/deviceconfig_example.yaml
Updated the name in the deviceconfig example file and added note to tell users that the device plugin, metrics exporter and node labeler pods will be prefixed with this name
=> Updated example deviceconfig name

.wordlist.txt, docs/conf.py, docs/contributing/documentation-build-guide.md, docs/contributing/documentation-standards.md, docs/knownlimitations.md, docs/metrics/exporter.md, docs/releasenotes.md, docs/site/metrics/exporter/index.html, docs/sphinx/_toc.yml, docs/sphinx/_toc.yml.in
- Added GPU Operator v1.0.0 and v1.1.0 release notes
- Updated Metrics Exporter docs
- Added Known Limitations section
- Added Documentation Build Guide
=> Added Release Notes, Known Limitations and Contributing section to docs

docs/installation/kubernetes-helm.md, docs/installation/openshift-olm.md
1. Update installation method on OpenShift OperatorHub.
2. Update default images for device metrics exporter.
=> Update docs about OpenShift installation and default images

bundle/manifests/amd-gpu-operator.clusterserviceversion.yaml, config/manifests/bases/amd-gpu-operator.clusterserviceversion.yaml, config/rbac/test_runner_role.yaml, hack/openshift-patch/template-patch/test-runner-rbac.yaml, helm-charts-openshift/Chart.lock, helm-charts-openshift/templates/test-runner-rbac.yaml
Adding SecurityContextConstraint access to test runner role so that OpenShift cluster could allow test runner pod to run privileged containers.
=> Adding SecurityContextConstraint access to test runner role

Makefile
the current comment in ```Makefile``` will lead to wrong value assignment to the ENV ```DOCKER_CONTAINER_IMG```, there will be one more extra whitespace assigned to that ENV.
Move the comment to a different line can resolve the issue.
=> Fix the wrong assignment of docker-save file name

Makefile, bundle/manifests/amd-gpu-operator.clusterserviceversion.yaml, config/rbac/kustomization.yaml, config/rbac/utils_container_role.yaml, config/rbac/utils_container_role_binding.yaml, config/rbac/utils_container_service_account.yaml, hack/k8s-patch/metadata-patch/values.yaml, hack/k8s-patch/template-patch/serviceaccount.yaml, hack/k8s-patch/template-patch/utils-container-rbac.yaml, hack/openshift-patch/template-patch/utils-container-rbac.yaml, helm-charts-k8s/Chart.lock, helm-charts-k8s/templates/serviceaccount.yaml, helm-charts-k8s/templates/utils-container-rbac.yaml, helm-charts-k8s/values.yaml, helm-charts-openshift/Chart.lock, helm-charts-openshift/templates/utils-container-rbac.yaml, internal/controllers/upgrademgr.go
Reboot Pod requires extra config change using Service account for Privileged access in Openshift.
Same fix which was done for testrunner: https://github.com/pensando/gpu-operator/pull/484
Tested RebootRequired functionality with the fix:
CR updated from 6.3.1 to 6.3.2 (Had already built 6.3.2 and kept it for kmm to unload/load)
Reboot is triggered from CR
```
[core@52-54-00-8b-35-21 ~]$ kubectl get pods -A | grep reboot
kube-amd-gpu                                       amd-gpu-operator-b0-26-28-e8-50-46-reboot-worker                  0/1     Completed     0               49s
kube-amd-gpu                                       amd-gpu-operator-b0-26-28-e8-a4-6a-reboot-worker                  1/1     Running       0               49s
```
Node moves to NotReady state once rebooted
``` …
```
=> Utils Container Openshift Security Context Constraint access

api/v1alpha1/deviceconfig_types.go, bundle/manifests/amd-gpu-operator.clusterserviceversion.yaml, bundle/manifests/amd.com_deviceconfigs.yaml, config/crd/bases/amd.com_deviceconfigs.yaml, docs/installation/openshift-olm.md, helm-charts-k8s/Chart.lock, helm-charts-k8s/crds/deviceconfig-crd.yaml, helm-charts-openshift/Chart.lock, helm-charts-openshift/crds/deviceconfig-crd.yaml
Earlier, using $MOD_NAMESPACE in Image field would throw regex validation error
```
[core@52-54-00-8b-35-21 ~]$ cat sample.yaml
apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
name: test-deviceconfig
namespace: kube-amd-gpu
spec:
driver:
blacklist: true
enable: true
image: image-registry.openshift-image-registry.svc:5000/$MOD_NAMESPACE/amdgpu_kmod
imageRegistryTLS:
insecure: True
version: "6.3.1"
upgradePolicy:
enable: true
maxParallelUpgrades: 2
rebootRequired: false
selector:
feature.node.kubernetes.io/amd-gpu: "true"
[core@52-54-00-8b-35-21 ~]$ kubectl apply -f sample.yaml
The DeviceConfig "test-deviceconfig" is invalid: spec.driver.image: Invalid value: "image-registry.openshift-image-registry.svc:5000/$MOD_NAMESPACE/amdgpu_kmod": spec.driver.image in body should match …
```
=> Openshift URL Regex Issue for $MOD_NAMESPACE

api/v1alpha1/deviceconfig_types.go, bundle/manifests/amd-gpu-operator.clusterserviceversion.yaml, bundle/manifests/amd.com_deviceconfigs.yaml, config/crd/bases/amd.com_deviceconfigs.yaml, config/manifests/bases/amd-gpu-operator.clusterserviceversion.yaml, helm-charts-k8s/Chart.lock, helm-charts-k8s/crds/deviceconfig-crd.yaml, helm-charts-openshift/Chart.lock, helm-charts-openshift/crds/deviceconfig-crd.yaml, internal/nodelabeller/nodelabeller.go
Optimize the blacklist support for the issue raised in https://github.com/ROCm/gpu-operator/issues/93.
1. For non-OpenShift users nothing is changed
2. For OpenShift users, add more field description to guide them use Machine Config Operator (MCO) to apply the blacklist on OpenShift cluster.
3. For OpenShift users, if any users accidentally configured ```spec.driver.blacklist``` option, use a special blacklist file name so that it won't conflict with MCO blacklist management.
=> Optimize the docs and filename for blacklist function

api/v1alpha1/deviceconfig_types.go, bundle/manifests/amd-gpu-operator.clusterserviceversion.yaml, bundle/manifests/amd.com_deviceconfigs.yaml, config/crd/bases/amd.com_deviceconfigs.yaml, helm-charts-k8s/Chart.lock, helm-charts-k8s/crds/deviceconfig-crd.yaml, helm-charts-openshift/Chart.lock, helm-charts-openshift/crds/deviceconfig-crd.yaml, internal/controllers/device_config_reconciler.go, internal/controllers/mock_upgrademgr.go, internal/controllers/upgrademgr.go
Issue: https://pensando.atlassian.net/browse/GPUOP-258
When an automatic upgrade with rebootRequired=true is triggered, nodes are rebooted one by one. If the node hosting the operator pod is rebooted, it kills the operator controller. After reboot, the controller restarts and triggers another reconcile loop, mistakenly thinking the node is still waiting for a reboot since it will be in `UpgradeStarted`, causing a continuous reboot loop
Fix:
-> Recently, we have added support in GPU operator to detect `bootId` change to check for reboot. We will now use this to see if the node has rebooted and not trigger reboot again in those scenarios which will avoid getting into a loop of reboots.
-> If we see that node status is `UpgradeStarted` when operator comes up during init but reboot has …
=> Reboot Loop issue if control node needs to go down for driver upgrade

docs/drivers/installation.md, docs/fulldeviceconfig.rst
Update docs for OpenShift users to use Machine Config Operator (MCO) to configure for blacklisting amdgpu inbox driver.
=> Add note for blacklisting amdgpu on OpenShift cluster in full example

internal/metricsexporter/metricsexporter.go
- ContainerPort lists the ports to expose from the Container. Not specifying a port DOES NOT prevent that port from being exposed. The device metrics exporter container starts a metrics server on the port specified by the METRICS_EXPORTER_PORT on the default "0.0.0.0" address in the container which exposes the port. Look at https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/ for more information on this behavior.
=> Expose ContainerPort in Metrics Exporter Pod

docs/installation/kubernetes-helm.md, hack/k8s-patch/metadata-patch/values.yaml, hack/openshift-patch/metadata-patch/values.yaml, helm-charts-k8s/values.yaml, helm-charts-openshift/values.yaml
For larger deployments, the default CPU limits of 500m (half a core) and memory limit of 384Mi in the cluster might be insufficient. It has been bumped up with this change and documentation has been added to alert the user to modify these values in helm if they have larger clusters.
=> Change default cpu/memory resource limits for Controller Manager

tools/techsupport_dump.sh
1. Fixed an issue that the script is just collecting default container's log of a pod, by using ```--all-containers``` option one single ```kubectl logs``` could collect all containers logs. E.g. the kube-rbac-proxy and other init container logs will be collected as well.
2. Fixed an issue that the script cannot detect NFD, KMM and Operator's namespace because previously it is using vanilla k8s helm chart  related labels to detect the namespace. If the namespaces were not detected successfully, using OpenShift's OLM bundle deployed pod name to detect NFD, KMM and Operator's namespace separately.
3. Fixed an issue that when users select all node, it is possible that the script won't collect logs from all node. It is because the controller pods and operand pods may not exist on all nodes, …
=> Fix multiple techsupport script issues

hack/k8s-patch/metadata-patch/values.yaml, helm-charts-k8s/Chart.lock, helm-charts-k8s/README.md, helm-charts-k8s/values.yaml
Expose NFD worker daemonset's nodeSelector and tolerations config into the ```values.yaml``` of main helm chart.
Related feature request https://github.com/ROCm/gpu-operator/issues/149
=> Expose NFD worker nodeSelector and tolerations in main chart values.yaml

Makefile, internal/controllers/device_config_reconciler.go, internal/utils.go, internal/utils_test.go
* fix: Only remove node labeller managed labels
The reconciler currently removes all labels with the amd.com and beta.amd.com prefix on nodes during cleanup. This is overly aggressive and can delete labels added by other users or systems.
This commit corrects the behavior to only remove labels that are specifically managed by node labeller, ensuring that only relevant labels are automatically cleaned up.
* test: Add more unit test cases for label cleanup modification
Fixing issue https://github.com/ROCm/gpu-operator/issues/151
=> Avoid cleanup all node labels under domain amd.com and beta.amd.com

hack/k8s-patch/template-patch/pre-upgrade-hook.yaml, helm-charts-k8s/Chart.lock, helm-charts-k8s/templates/pre-upgrade-hook.yaml
Cherry-pick the idea came from an external PR https://github.com/ROCm/gpu-operator/pull/94 
1. Currently the ```pre-upgrade-check``` hook is replying on the Chart template defined service account, which is not going to work for Argo deployment, the ```pre-upgrade-check``` hook needs to define and use its own RBAC configs instead of replying on main chart RBAC settings, so that the hook could decouple with main chart resources.
2. Argo turns the helm pre-upgrade hook into pre-sync hook https://argo-cd.readthedocs.io/en/release-2.0/user-guide/helm/#helm-hooks , which means even the pre-upgrade are treated as the same as pre-install hook and getting executed when CRD were not even installed, we can ignore the NotFound CRD in the pre-upgrade hook and this won't affect the normal Helm Upgrade …
=> Fix helm chart pre-upgrade hook to support Argo deployment

bundle/manifests/amd-gpu-operator.clusterserviceversion.yaml, config/manager-base/manager.yaml
switch nodeaffinity from required to prefer for OLM, to support the hosted control plane deployment of OpenShift cluster. Suggestion came from https://github.com/ROCm/gpu-operator/pull/133 
Related issue #129
=> feat: switch nodeaffinity from required to prefer for OLM

hack/k8s-patch/template-patch/nfd-default-rule.yaml, helm-charts-k8s/templates/nfd-default-rule.yaml
Related feature ask: #56 #152 #154
=> Expand default NFD rule to more GPU models based on ROCm support matrix

tools/techsupport_dump.sh
1. Add uuid to each techsupport run, so that each run will only utilizing its own temp file and debug pods, they won't affect each other
2. Remove ```-it``` from ```kubectl exec -it``` so that users could run the techsupport script in the background without waiting for users input.
=> Add support for concurrent techsupport run

internal/controllers/upgrademgr.go
Upgrade Policy parameter change takes effect on remaining nodes without being stuck for already ongoing nodes since we have now let reboot goroutines continue as expected for ongoing upgrade attempts based on driver version instead of genID in previous PR: https://github.com/ROCm/gpu-operator/pull/173
Handling one edge case scenario in this PR:
If operator goes down exactly when the CR update happens and rebootRequired is change from true to false in the CR update, then we need to delete the rebootpod as well.
=> upgrade param change during driver upgrade corner case

internal/controllers/device_config_reconciler.go
Issue from public repo: https://github.com/ROCm/gpu-operator/issues/183
when users set ```spec.driver.enable=false```  to use inbox driver
controller is still looking for the select nodes to clean up the node labeller label, for the nodes that didn't have KMM ready labels
However, for the inbox driver use case KMM is not triggered, controller SHOULD NOT look for KMM ready labels.
Modifying
```golang
sel := []string{
"! " + utils.NodeFeatureLabelAmdGpu,
"! " + labels.GetKernelModuleReadyNodeLabel(devConfig.Namespace, devConfig.Name),
"! " + labels.GetDevicePluginNodeLabel(devConfig.Namespace, devConfig.Name),
"! " + utils.NodeFeatureLabelAmdVGpu,
}
```
to be 
```golang
sel := []string{
"! " + utils.NodeFeatureLabelAmdGpu,
"! " + utils.NodeFeatureLabelAmdVGpu,
}
if …
```
=> Avoid auto cleanup node labeller labels on vgpu only node

Makefile, README.md, docs/conf.py, docs/installation/kubernetes-helm.md, docs/sphinx/_toc.yml, docs/uninstallation/uninstallation.md, docs/upgrades/upgrade.md, docs/usage.md, hack/k8s-patch/metadata-patch/values.yaml, hack/k8s-patch/template-patch/default-deviceconfig.yaml, hack/k8s-patch/template-patch/pre-delete-hook.yaml, hack/k8s-patch/template-patch/pre-upgrade-hook.yaml, helm-charts-k8s/Chart.lock, helm-charts-k8s/README.md, helm-charts-k8s/templates/default-deviceconfig.yaml, helm-charts-k8s/templates/pre-delete-hook.yaml, helm-charts-k8s/templates/pre-upgrade-hook.yaml, helm-charts-k8s/values.yaml, tests/helm-e2e/Makefile, tests/helm-e2e/doc.go, tests/helm-e2e/e2e_test.go, tests/helm-e2e/helm_e2e_test.go
Add a default `DefaultConfig` in the helm chart, with corresponding e2e test suite and docs change.
Related Issue: https://github.com/ROCm/gpu-operator/issues/150
1. Helm install:
* By default helm install will create a helm default DeviceConfig, it is configurable via changing values.yaml.
* Users can optionally turn it off during helm install. --set crds.defaultCR.install=false
2. Helm upgrade:
* By default NO default DeviceConfig will be created/patched.
* In that way, By Default, Users with existing DeviceConfigs,  upgrading to new version of helm chart will affect their existing DeviceConfig.
* Users can optionally turn on creating/patching the default DeviceConfig with new default values or customized values. They need to evaluate the risk of conflicting with their existing …
=> Add default DeviceConfig into Helm Chart with e2e test and docs change

docs/installation/openshift-olm.md
Related issue https://github.com/ROCm/gpu-operator/issues/132
We asked RedHat team members who are maintaining NFD operator. Based on RedHat team's response we modified the instructions of creating `NodeFeatureDiscovery` custom resource.
=> [DOC] Update docs for Openshift NodeFeatureDiscovery instruction

docs/installation/kubernetes-helm.md, docs/slinky/slinky-example.md, docs/troubleshooting.md, docs/usage.rst
Several fixes on the existing docs:
1. The quick start doc has been switched to ```usage.rst``` but still use markdown format of docs, which makes the previous markdown docs didn't show up correctly in the website https://instinct.docs.amd.com/projects/gpu-operator/en/latest/usage.html . Fixing the syntax to meet the requirement of new rst docs.
2. Add the description of the default `DeviceConfig` that comes with the installation of v1.3.0 or later version helm charts.
3. In the example verification steps, move the image from `pytorch:latest` to `rocm-terminal:latest` because the former one is around 20GB after compression, which is too large. Related issue ticket is https://github.com/ROCm/gpu-operator/issues/200
=> [CP 769][DOC] Misc fix on helm installation description

docs/installation/openshift-olm.md, hack/k8s-patch/template-patch/nfd-default-rule.yaml, helm-charts-k8s/Chart.lock, helm-charts-k8s/templates/nfd-default-rule.yaml
Add MI350X and MI355X PF and VF device ID to the default NFD rule so that the new release could support the auto-detection of the latest Instinct GPUs.
=> [CP 776][Helm] Add MI350X and MI355X PF and VF device ID into NFD rule

Makefile
* Issues:
Currently when we changed the binary tools version, the old binaries won't get auto updated. For example we have updated the `controller-gen` version over different branches, when we switch among branches to do the build, the outdated `controller-gen` could result in massive auto-generated files differences.
* Improvement:
In the Makefile, if the binary tool is existing, check the version. If the version mismatch with the desired version, re-download the binary tool so that the correct version tool could be used for building the project.
=> [Build] Optimize makefile to auto remove outdated binary tools

docs/usage.rst
fix a document error regarding using amd-smi pod to verify the installation
=> [DOC] GPUOP-400 Fix invalid YAML format of amd-smi example pod

docs/slinky/slinky-example.md
https://github.com/ROCm/gpu-operator/pull/271  cherry-pick the proposed changes to staging branch
related issue: https://github.com/ROCm/gpu-operator/issues/272
basically don't point to a specific version of Slinky project's Helm charts or Dockerfile, point it to latest so that users would be default using the latest Slinky release
=> [DOC] Bump Slinky version from 0.1.0 to latest

internal/controllers/remediation_handler.go, internal/controllers/watchers/node.go, internal/kmmmodule/dockerfiles/DockerfileTemplate.coreos.gim, internal/kmmmodule/kmmmodule.go
MxGPU GIM driver starts to support RHEL as host OS https://github.com/amd/MxGPU-Virtualization/releases, adding dockerfile to auto build GIM driver for OpenShift
successfully built driver image:
`
coreos-417.94-5.14.0-427.50.1.el9_4.x86_64-vf-passthrough-8.2.0.K`
`
coreos-417.94-5.14.0-427.50.1.el9_4.x86_64-vf-passthrough-8.3.0.K`
=> [Feature] Add GIM driver dockerfile for OpenShift
